workflows:
  ios-workflow:
    name: iOS TestFlight Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    integrations:
      app_store_connect: Fiscal Express
    
    environment:
      groups:
        - ios_signing
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.fiscalexpress.app"
      node: 20
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      
      - name: Build web app
        script: |
          npm run build
      
      - name: Add iOS platform
        script: |
          npm install @capacitor/ios@5
          npx cap add ios || true
          npx cap sync ios
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install
      
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
      
      - name: Add certs to keychain
        script: |
          keychain initialize
          keychain add-certificates
      
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      
      - name: Increment build number
        script: |
          cd ios/App
          agvtool new-version -all $(($BUILD_NUMBER + 10))
      
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
